better logic

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -60,7 +60,7 @@ jobs:
           npm install @datadog/datadog-api-client
           node ./check-junit-upload.js
         env:
-          EXTRA_TAGS: "@foo:bar @alpha:bravo @test.node.version:${{ matrix.version}}"
+          EXTRA_TAGS: "@foo:previous @alpha:previous"
           DD_API_KEY: ${{ secrets.DD_API_KEY_CI_VISIBILITY }}
           DD_APP_KEY: ${{ secrets.DD_APP_KEY_CI_VISIBILITY }}
           DD_SERVICE: junit-upload-github-action-tests
@@ -71,6 +71,7 @@ jobs:
       - uses: actions/checkout@v4
       - name: Upload reports using a glob pattern
         uses: ./
+        id: test_step
         with:
           logs: "true"
           files: '**/fixtures/**'
@@ -79,9 +80,7 @@ jobs:
           tags: "foo:bar,alpha:bravo"
         continue-on-error: true
       - name: Check that previous step failed
-        if: success()
-        run: echo "This step should not run" && exit 1
-      - name: Check that previous step failed
-        if: failure()
-        run: echo "Previous step failed as expected" 
-        
+        if: steps.test_step.outcome == 'success'
+        run: |
+          echo "The previous step did not fail as expected"
+          exit 1
