Update naming of input variables (#20)

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -19,7 +19,7 @@ jobs:
       - name: Upload reports using a glob pattern
         uses: ./
         with:
-          api-key: ${{secrets.DD_API_KEY_CI_VISIBILITY}}
+          api_key: ${{secrets.DD_API_KEY_CI_VISIBILITY}}
           logs: "true"
           files: '**/fixtures/**'
           service: junit-upload-github-action-tests
@@ -46,11 +46,40 @@ jobs:
       - name: Upload reports using a glob pattern
         uses: ./
         with:
+          # should still work with api-key as input
           api-key: ${{secrets.DD_API_KEY_CI_VISIBILITY}}
           logs: "true"
           files: '**/fixtures/**'
           service: junit-upload-github-action-tests
           env: ci
-          tags: "foo:bar,alpha:bravo"
+          tags: "foo:previous,alpha:previous"
           datadog-ci-version: ${{ env.SECOND_LATEST_VERSION }}
-      
+      - name: Check that test data can be queried
+        run: |
+          npm install @datadog/datadog-api-client
+          node ./check-junit-upload.js
+        env:
+          EXTRA_TAGS: "@foo:previous @alpha:previous"
+          DD_API_KEY: ${{ secrets.DD_API_KEY_CI_VISIBILITY }}
+          DD_APP_KEY: ${{ secrets.DD_APP_KEY_CI_VISIBILITY }}
+          DD_SERVICE: junit-upload-github-action-tests
+
+  test-should-complain-about-missing-api-key:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+      - name: Upload reports using a glob pattern
+        uses: ./
+        id: test_step
+        with:
+          logs: "true"
+          files: '**/fixtures/**'
+          service: junit-upload-github-action-tests
+          env: ci
+          tags: "foo:bar,alpha:bravo"
+        continue-on-error: true
+      - name: Check that previous step failed
+        if: steps.test_step.outcome == 'success'
+        run: |
+          echo "The previous step did not fail as expected"
+          exit 1
